name: "AmarBangla API"

on:
  pull_request:
  push:
    branches:
      - "master"
#  schedule:
#    - cron: "42 3 * * *"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "8.1"
        dependencies:
          - "highest"
        include:
          - dependencies: "lowest"
            php-version: "8.1"

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Configure database and migrate
        env:
          DB_CONNECTION: sqlite
          DB_HOST: localhost
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate
      - name: Seeding database
        run: php artisan db:seed
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
