name: "AmarBangla API"

on:
  pull_request:
  push:
    branches:
      - "master"
#  schedule:
#    - cron: "42 3 * * *"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "8.1"
        dependencies:
          - "highest"
        include:
          - dependencies: "lowest"
            php-version: "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: "Copy .env"
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: "Install Dependencies"
        run: "composer install -q --no-ansi --no-interaction --no-scripts --no-progress"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
